language: ruby
rvm:
  - "2.2.2"

## Allows use of docker-based containers, which are more available than
## the xen-based (or whatever) VMs, so builds tend to happen sooner
sudo: false

## Save bundler deps.  Requires sudo: false
cache: bundler

## Disable external link checking to prevent spurious failures because
## of other people's downtime. This can also avoid wasting their
## bandwidth.
#
## Build all possible jekyll pages for use with link checking.
script: bundle exec jekyll build --future --drafts --unpublished && bundle exec htmlproof --disable-external ./_site

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    
# Whitelist all branches since gh-pages branch is blacklisted by default
branches:
  only:
  - gh-pages
  - /.*/

notifications:
  irc:
    channels:
      - "chat.freenode.net#bitcoin-core-website"
    on_success: change
    on_failure: change
